/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/ishikabhosale-cs/customcluster/pkg/apis/ishikabhosale.dev/v1alpha1"
	ishikabhosaledevv1alpha1 "github.com/ishikabhosale-cs/customcluster/pkg/client/applyconfiguration/ishikabhosale.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomclusters implements CustomclusterInterface
type FakeCustomclusters struct {
	Fake *FakeIshikabhosaleV1alpha1
	ns   string
}

var customclustersResource = v1alpha1.SchemeGroupVersion.WithResource("customclusters")

var customclustersKind = v1alpha1.SchemeGroupVersion.WithKind("Customcluster")

// Get takes name of the customcluster, and returns the corresponding customcluster object, and an error if there is any.
func (c *FakeCustomclusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Customcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customclustersResource, c.ns, name), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// List takes label and field selectors, and returns the list of Customclusters that match those selectors.
func (c *FakeCustomclusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomclusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customclustersResource, customclustersKind, c.ns, opts), &v1alpha1.CustomclusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomclusterList{ListMeta: obj.(*v1alpha1.CustomclusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomclusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customclusters.
func (c *FakeCustomclusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customclustersResource, c.ns, opts))

}

// Create takes the representation of a customcluster and creates it.  Returns the server's representation of the customcluster, and an error, if there is any.
func (c *FakeCustomclusters) Create(ctx context.Context, customcluster *v1alpha1.Customcluster, opts v1.CreateOptions) (result *v1alpha1.Customcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customclustersResource, c.ns, customcluster), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// Update takes the representation of a customcluster and updates it. Returns the server's representation of the customcluster, and an error, if there is any.
func (c *FakeCustomclusters) Update(ctx context.Context, customcluster *v1alpha1.Customcluster, opts v1.UpdateOptions) (result *v1alpha1.Customcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customclustersResource, c.ns, customcluster), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomclusters) UpdateStatus(ctx context.Context, customcluster *v1alpha1.Customcluster, opts v1.UpdateOptions) (*v1alpha1.Customcluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customclustersResource, "status", c.ns, customcluster), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// Delete takes name of the customcluster and deletes it. Returns an error if one occurs.
func (c *FakeCustomclusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(customclustersResource, c.ns, name, opts), &v1alpha1.Customcluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomclusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomclusterList{})
	return err
}

// Patch applies the patch and returns the patched customcluster.
func (c *FakeCustomclusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Customcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied customcluster.
func (c *FakeCustomclusters) Apply(ctx context.Context, customcluster *ishikabhosaledevv1alpha1.CustomclusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Customcluster, err error) {
	if customcluster == nil {
		return nil, fmt.Errorf("customcluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(customcluster)
	if err != nil {
		return nil, err
	}
	name := customcluster.Name
	if name == nil {
		return nil, fmt.Errorf("customcluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customclustersResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeCustomclusters) ApplyStatus(ctx context.Context, customcluster *ishikabhosaledevv1alpha1.CustomclusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Customcluster, err error) {
	if customcluster == nil {
		return nil, fmt.Errorf("customcluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(customcluster)
	if err != nil {
		return nil, err
	}
	name := customcluster.Name
	if name == nil {
		return nil, fmt.Errorf("customcluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customclustersResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Customcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Customcluster), err
}
